services:
  google-maps:
    image: supercorp/supergateway
    ports: ["8100:8100"]
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    entrypoint: /bin/sh -c
    command: >
      'test -z "$GOOGLE_MAPS_API_KEY" &&
         { echo "❌ GOOGLE_MAPS_API_KEY missing"; exit 1; };
       exec supergateway --stdio "npx -y @modelcontextprotocol/server-google-maps" --port 8100'

  mcp-server-qdrant:
    image: mcp-server-qdrant
    ports: ["8102:8000"]      
    environment:
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - COLLECTION_NAME=user-preferences
      - TOOL_FIND_DESCRIPTION=Search for user's stored preferences and personal information including food preferences, favorite activities, travel style, dietary restrictions, and general likes/dislikes
    entrypoint: /bin/sh -c
    command: >
      'if [ -z "$QDRANT_URL" ] || [ -z "$QDRANT_API_KEY" ]; then
          echo "❌ QDRANT_URL and/or QDRANT_API_KEY missing"; exit 1;
       fi;
       exec mcp-server-qdrant --transport sse'
  
  optimal-route:
    image: vblagoje/optimal-route
    ports: ["8104:8080"]
    environment:
      - GOOGLE_API_KEY=${GOOGLE_MAPS_API_KEY}
      - MCP_TRANSPORT=sse
        
  perplexity:
    image: supercorp/supergateway
    ports: ["8105:8105"]
    environment:
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    entrypoint: /bin/sh -c
    command: >
      'test -z "$PERPLEXITY_API_KEY" &&
         { echo "❌ PERPLEXITY_API_KEY missing"; exit 1; };
       exec supergateway --stdio "npx -y server-perplexity-ask" --port 8105'